# Generated by Django 5.0.6 on 2024-06-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contects',
            new_name='Contacts',
        ),
    ]
